import type { GameConfig } from '../core/types';

// PLACEHOLDER v2 (ECONOMY_SPEC.md) — designer-approved, tunable within guardrails
export const ECONOMY: Pick<GameConfig,
  'resources' | 'startingResources' | 'buildings' | 'rosters' | 'combos' | 'terrainBonuses' |
  'zoneModifiers' | 'adjacencyAmount' | 'thresholds' | 'demolishRefundRatio' | 'reshufflesPerRun'> = {
  resources: ['wood', 'stone', 'water', 'food'],
  startingResources: { wood: 6, stone: 6 },
  buildings: {
    lumber_camp: { id: 'lumber_camp', name: 'Lumber Camp', cost: { wood: 2 }, baseYield: { wood: 5 } },
    hillside_mine: { id: 'hillside_mine', name: 'Hillside Mine', cost: { wood: 2 }, baseYield: { stone: 2 } },
    sawmill: { id: 'sawmill', name: 'Sawmill', cost: { wood: 2, stone: 2 }, baseYield: { wood: 6 } },
    gatherers_hut: { id: 'gatherers_hut', name: "Gatherer's Hut", cost: { wood: 2 }, baseYield: { food: 2, wood: 1 } },
    farm: { id: 'farm', name: 'Farm', cost: { wood: 3, stone: 1 }, baseYield: { food: 4 } },
    quarry: { id: 'quarry', name: 'Quarry', cost: { stone: 2 }, baseYield: { stone: 4 } },
    palm_grove: { id: 'palm_grove', name: 'Palm Grove', cost: { stone: 2 }, baseYield: { wood: 4 } },
    stonemason: { id: 'stonemason', name: 'Stonemason', cost: { wood: 2, stone: 2 }, baseYield: { stone: 5 } },
    oasis_well: { id: 'oasis_well', name: 'Oasis Well', cost: { stone: 3 }, baseYield: { water: 3, stone: 1 } },
    glass_kiln: { id: 'glass_kiln', name: 'Glass Kiln', cost: { stone: 4, water: 2 }, baseYield: { stone: 3, water: 3 } },
    driftwood_camp: { id: 'driftwood_camp', name: 'Driftwood Camp', cost: { stone: 2 }, baseYield: { wood: 4 } },
    scree_quarry: { id: 'scree_quarry', name: 'Scree Quarry', cost: { wood: 2 }, baseYield: { stone: 4 } },
    ice_drill: { id: 'ice_drill', name: 'Ice Drill', cost: { wood: 1, stone: 1 }, baseYield: { water: 4 } },
    glacier_pump: { id: 'glacier_pump', name: 'Glacier Pump', cost: { wood: 2, stone: 2 }, baseYield: { water: 4 } },
    ice_fishery: { id: 'ice_fishery', name: 'Ice Fishery', cost: { wood: 2, stone: 1 }, baseYield: { food: 2, water: 1 } },
    grain_fields: { id: 'grain_fields', name: 'Grain Fields', cost: { wood: 2, stone: 1 }, baseYield: { food: 4 } },
    windmill: { id: 'windmill', name: 'Windmill', cost: { wood: 3, stone: 1 }, baseYield: { food: 3, stone: 2 } },
    caravanserai: { id: 'caravanserai', name: 'Caravanserai', cost: { wood: 2, stone: 2, food: 1 }, baseYield: { wood: 3, stone: 3 } },
    trapper_lodge: { id: 'trapper_lodge', name: 'Trapper Lodge', cost: { wood: 2 }, baseYield: { food: 3, wood: 1 } },
    resin_works: { id: 'resin_works', name: 'Resin Works', cost: { stone: 2, water: 1 }, baseYield: { wood: 5 } },
    hot_spring: { id: 'hot_spring', name: 'Hot Spring', cost: { stone: 3 }, baseYield: { water: 3, food: 2 } },
    lichen_farm: { id: 'lichen_farm', name: 'Lichen Farm', cost: { stone: 2, water: 1 }, baseYield: { food: 4 } },
    salt_mine: { id: 'salt_mine', name: 'Salt Mine', cost: { wood: 3 }, baseYield: { stone: 4, food: 1 } },
    frost_kiln: { id: 'frost_kiln', name: 'Frost Kiln', cost: { wood: 2, stone: 2 }, baseYield: { stone: 2, water: 3 } },
  },
  rosters: {
    forest: ['lumber_camp', 'hillside_mine', 'sawmill', 'gatherers_hut', 'farm'],
    desert: ['quarry', 'palm_grove', 'stonemason', 'oasis_well', 'glass_kiln'],
    arctic: ['driftwood_camp', 'scree_quarry', 'ice_drill', 'glacier_pump', 'ice_fishery'],
    steppe: ['lumber_camp', 'sawmill', 'farm', 'quarry', 'stonemason', 'oasis_well', 'grain_fields', 'windmill', 'caravanserai'],
    taiga: ['lumber_camp', 'sawmill', 'gatherers_hut', 'ice_drill', 'glacier_pump', 'scree_quarry', 'trapper_lodge', 'resin_works', 'hot_spring'],
    polarDesert: ['quarry', 'stonemason', 'oasis_well', 'ice_drill', 'glacier_pump', 'driftwood_camp', 'lichen_farm', 'salt_mine', 'frost_kiln'],
  },
  combos: [
    { id: 'timber_line', name: 'Timber Line', buildings: ['lumber_camp', 'sawmill'], amount: { wood: 5 } },
    { id: 'homestead', name: 'Homestead', buildings: ['sawmill', 'farm'], amount: { wood: 3, food: 3 } },
    { id: 'forest_camp', name: 'Forest Camp', buildings: ['lumber_camp', 'gatherers_hut'], amount: { wood: 3, food: 3 } },
    { id: 'woodland_village', name: 'Woodland Village', buildings: ['lumber_camp', 'sawmill', 'farm'], amount: { wood: 7, food: 6 } },
    { id: 'cut_stone', name: 'Cut Stone', buildings: ['quarry', 'stonemason'], amount: { stone: 5 } },
    { id: 'oasis_town', name: 'Oasis Town', buildings: ['oasis_well', 'palm_grove'], amount: { water: 3, wood: 3 } },
    { id: 'desert_outpost', name: 'Desert Outpost', buildings: ['quarry', 'palm_grove'], amount: { stone: 3, wood: 2 } },
    { id: 'sun_citadel', name: 'Sun Citadel', buildings: ['quarry', 'stonemason', 'glass_kiln'], amount: { stone: 8, water: 5 } },
    { id: 'ice_mine', name: 'Ice Mine', buildings: ['ice_drill', 'scree_quarry'], amount: { water: 3, stone: 3 } },
    { id: 'harbor', name: 'Harbor', buildings: ['ice_fishery', 'ice_drill'], amount: { food: 3, water: 3 } },
    { id: 'frontier_outpost', name: 'Frontier Outpost', buildings: ['driftwood_camp', 'scree_quarry'], amount: { wood: 3, stone: 3 } },
    { id: 'polar_base', name: 'Polar Base', buildings: ['ice_drill', 'glacier_pump', 'ice_fishery'], amount: { water: 8, food: 4, stone: 2 } },
    { id: 'bread_road', name: 'Bread Road', buildings: ['grain_fields', 'windmill'], amount: { food: 6 } },
    { id: 'frontier_farm', name: 'Frontier Farm', buildings: ['farm', 'grain_fields'], amount: { food: 4, wood: 2 } },
    { id: 'market_town', name: 'Market Town', buildings: ['caravanserai', 'sawmill', 'quarry'], amount: { wood: 5, stone: 5, food: 4 } },
    { id: 'fur_trade', name: 'Fur Trade', buildings: ['trapper_lodge', 'gatherers_hut'], amount: { food: 6 } },
    { id: 'resin_mill', name: 'Resin Mill', buildings: ['resin_works', 'sawmill'], amount: { wood: 6 } },
    { id: 'spa_village', name: 'Spa Village', buildings: ['hot_spring', 'ice_drill', 'gatherers_hut'], amount: { water: 6, food: 7 } },
    { id: 'salt_cure', name: 'Salt Cure', buildings: ['salt_mine', 'lichen_farm'], amount: { food: 4, stone: 2 } },
    { id: 'frost_glass', name: 'Frost Glass', buildings: ['frost_kiln', 'oasis_well'], amount: { water: 4, stone: 2 } },
    { id: 'lichen_terraces', name: 'Lichen Terraces', buildings: ['lichen_farm', 'oasis_well', 'frost_kiln'], amount: { food: 7, water: 6 } },
  ],
  terrainBonuses: [
    { adjacentTerrain: ['mountain'], buildings: ['hillside_mine', 'quarry', 'scree_quarry', 'salt_mine'], bonus: { stone: 2 } },
    { adjacentTerrain: ['riverbed', 'basin'], buildings: ['oasis_well', 'ice_drill', 'glacier_pump', 'hot_spring'], bonus: { water: 2 } },
    { adjacentTerrain: ['riverbed', 'basin'], buildings: ['farm', 'grain_fields', 'lichen_farm', 'ice_fishery'], bonus: { food: 1 } },
    { adjacentTerrain: ['woods'], buildings: ['lumber_camp', 'sawmill', 'driftwood_camp', 'resin_works'], bonus: { wood: 1 } },
    { adjacentTerrain: ['marsh'], buildings: 'any', bonus: { food: 1 } },
  ],
  zoneModifiers: {
    steppe: [
      { buildings: ['grain_fields'], delta: { food: 1 } },
      { buildings: ['sawmill'], delta: { wood: -1 } },
    ],
    taiga: [
      { buildings: ['lumber_camp'], delta: { wood: 1 } },
      { buildings: ['ice_drill'], delta: { water: -1 } },
    ],
    polarDesert: [
      { buildings: ['salt_mine'], delta: { stone: 1 } },
      { buildings: ['oasis_well'], delta: { water: -1 } },
    ],
  },
  adjacencyAmount: { wood: 2, stone: 2, water: 2, food: 2 },
  thresholds: [
    { wood: 0, stone: 16 },
    { wood: 50, stone: 45 },
    { wood: 100, stone: 85, water: 40 },
    { wood: 260, stone: 220, water: 120, food: 90 },
    { wood: 450, stone: 380, water: 200, food: 120 },
    { wood: 850, stone: 740, water: 550, food: 170 },
  ],
  demolishRefundRatio: 0.5,
  reshufflesPerRun: 1,
};
