import * as THREE from 'three';
import {readFileSync,writeFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
import {BUILDING_LIMITS,ModelAssets,inspectGLB} from '../../src/render/modelAssets';
import {SLOT_ANCHORS} from '../../src/render/layout';
// @ts-expect-error Offline JS tool, not a production module.
import {BUILDERS} from './build-buildings.mjs';
// @ts-expect-error Offline JS geometry helpers.
import {PALETTE,prism,screwFlight,stripedTank,roofArc,sawPlate} from './geometry-buildings.mjs';
// @ts-expect-error Shared offline GLB writer.
import {writeGLB} from './glb-writer.mjs';

describe('compact building assets',()=>{
  it('lumber camp retains the reference yard and detailed entrance',()=>{
    const {geometry,groups}=BUILDERS.lumber_camp();
    try {
      expect(groups.pine).toBeGreaterThanOrEqual(42);
      expect(groups.fence).toBeGreaterThanOrEqual(60);
      expect(groups.rocks).toBeGreaterThanOrEqual(16);
      expect(groups.plants).toBeGreaterThanOrEqual(24);
      expect(groups.entrance).toBeGreaterThanOrEqual(42);
      expect(groups.logs).toBeGreaterThanOrEqual(140);
      expect(groups['stump-axe']).toBeGreaterThanOrEqual(56);
    } finally {geometry.dispose();}
  });
  it('ice drill keeps the hut substantial and retains the restored snow/crate/ice details',()=>{
    const {geometry,groups}=BUILDERS.ice_drill();
    const p=geometry.getAttribute('position'),c=geometry.getAttribute('color');
    const hutColor=new THREE.Color(PALETTE.hut),snowColor=new THREE.Color(PALETTE.snow);
    let hutTop=0,snowVertices=0;
    const matches=(i:number,color:THREE.Color)=>Math.abs(c.getX(i)-color.r)<1e-6&&Math.abs(c.getY(i)-color.g)<1e-6&&Math.abs(c.getZ(i)-color.b)<1e-6;
    for(let i=0;i<p.count;i++) {
      if(matches(i,hutColor)) hutTop=Math.max(hutTop,p.getY(i));
      if(matches(i,snowColor)) snowVertices++;
    }
    // The rejected version's hut was under 30% of derrick height.
    expect(hutTop/geometry.boundingBox.max.y).toBeGreaterThan(.58);
    expect(hutTop/geometry.boundingBox.max.y).toBeLessThan(.75);
    expect(groups.crates).toBeGreaterThanOrEqual(48);
    expect(groups['ice-chunks']).toBeGreaterThanOrEqual(24);
    expect(groups['roof-snow']).toBeGreaterThanOrEqual(16);
    expect(snowVertices).toBeGreaterThanOrEqual(100);
    geometry.dispose();
  });
  it('keeps the maximum accepted footprints separate at all three production slot anchors',()=>{
    for(let i=0;i<SLOT_ANCHORS.length;i++) {
      const a=SLOT_ANCHORS[i];
      expect(Math.hypot(a.x,a.z)+BUILDING_LIMITS.radius).toBeLessThan(Math.sqrt(3)/2);
      for(let j=i+1;j<SLOT_ANCHORS.length;j++) {
        const b=SLOT_ANCHORS[j];
        expect(Math.hypot(a.x-b.x,a.z-b.z)-2*BUILDING_LIMITS.radius).toBeGreaterThan(.11);
      }
    }
  });
  it('winds closed custom primitives outward and the open curved roof upward',()=>{
    for(const g of [prism([[-1,0],[1,0],[1,1],[0,2],[-1,1]],.2),screwFlight(),stripedTank(),sawPlate(.1,.01)]) {
      const p=g.getAttribute('position'),edges=new Map<string,number[]>();let volume=0;
      for(let i=0;i<g.index.count;i+=3) {
        const ids=[0,1,2].map(j=>g.index.getX(i+j));
        const[a,b,c]=ids.map(id=>new THREE.Vector3().fromBufferAttribute(p,id));
        volume+=a.dot(b.cross(c))/6;
        for(let j=0;j<3;j++) {
          const a=ids[j],b=ids[(j+1)%3],key=[a,b].sort((x,y)=>x-y).join(':');
          const directions=edges.get(key)??[];directions.push(a<b?1:-1);edges.set(key,directions);
        }
      }
      expect(volume).toBeGreaterThan(0);
      for(const directions of edges.values()){expect(directions).toHaveLength(2);expect(directions[0]+directions[1]).toBe(0);}
      g.dispose();
    }
    const roof=roofArc(.08,.057,.148).toNonIndexed();roof.computeVertexNormals();
    const n=roof.getAttribute('normal');
    for(let i=0;i<n.count;i++) expect(n.getY(i)).toBeGreaterThan(0);
    roof.dispose();
  });

  for(const name of Object.keys(BUILDERS)) {
    it(`${name}: promoted asset matches the validated generated bytes`,()=>{
      expect(readFileSync(`src/assets/models/${name}.glb`)).toEqual(readFileSync(`tools/models/out/${name}.glb`));
    });
    it(`${name}: reproducible vertex-only GLB, compact bounds, flat nondegenerate faces`,()=>{
      const{geometry}=BUILDERS[name]();
      try {
        const bytes=readFileSync(`tools/models/out/${name}.glb`);
        expect(Buffer.from(writeGLB(geometry,name))).toEqual(bytes);
        const doc=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());
        expect(doc.meshes).toHaveLength(1);expect(doc.materials).toHaveLength(1);
        expect(doc.materials[0].pbrMetallicRoughness.baseColorFactor).toEqual([1,1,1,1]);
        expect(doc.materials[0].alphaMode).toBe('OPAQUE');
        for(const key of ['textures','images','animations','skins','cameras','extensionsRequired']) expect(doc[key]).toBeUndefined();
        expect(doc.buffers[0].uri).toBeUndefined();
        expect(doc.meshes[0].primitives[0].attributes).toEqual({POSITION:0,NORMAL:1,COLOR_0:2,_EMIT:3});
        const p=geometry.getAttribute('position'),n=geometry.getAttribute('normal'),c=geometry.getAttribute('color'),e=geometry.getAttribute('_EMIT');
        expect(geometry.index.count/3).toBeGreaterThanOrEqual(350);
        expect(geometry.index.count/3).toBeLessThanOrEqual(BUILDING_LIMITS.triangles);
        const palette=Object.values(PALETTE).map(hex=>new THREE.Color(hex as string));
        for(let i=0;i<p.count;i++) {
          expect(Math.hypot(p.getX(i),p.getZ(i))).toBeLessThanOrEqual(.28);
          expect(p.getY(i)).toBeGreaterThanOrEqual(-1e-8);expect(p.getY(i)).toBeLessThanOrEqual(.5);
          expect(c.getW(i)).toBeGreaterThan(0);expect(c.getW(i)).toBeLessThanOrEqual(1);expect(e.getX(i)).toBe(name==='hillside_mine'&&Math.abs(c.getX(i)-new THREE.Color(PALETTE.amber).r)<1e-6?1:0);
          if(i%3===0) {
            const a=new THREE.Vector3().fromBufferAttribute(p,i),b=new THREE.Vector3().fromBufferAttribute(p,i+1),d=new THREE.Vector3().fromBufferAttribute(p,i+2);
            const normal=b.sub(a).cross(d.sub(a));expect(normal.length()).toBeGreaterThan(1e-10);
            expect(normal.normalize().dot(new THREE.Vector3().fromBufferAttribute(n,i))).toBeCloseTo(1);
            expect(palette.some(color=>Math.abs(color.r-c.getX(i))<1e-6&&Math.abs(color.g-c.getY(i))<1e-6&&Math.abs(color.b-c.getZ(i))<1e-6)).toBe(true);
            for(let j=1;j<3;j++) for(let axis=0;axis<3;axis++) {
              expect(n.getComponent(i,axis)).toBeCloseTo(n.getComponent(i+j,axis));
              expect(c.getComponent(i,axis)).toBe(c.getComponent(i+j,axis));
            }
          }
        }
        const box=geometry.boundingBox;
        expect(box.min.y).toBeCloseTo(0);expect(box.min.x+box.max.x).toBeCloseTo(0);expect(box.min.z+box.max.z).toBeCloseTo(0);
      } finally {geometry.dispose();}
    });

    it(`${name}: accepted by production loader without fallback`,async()=>{
      const bytes=readFileSync(`tools/models/out/${name}.glb`);
      const buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;
      expect(()=>inspectGLB(buffer)).not.toThrow();
      const assets=new ModelAssets({[`/tools/models/out/${name}.glb`]:'fixture'},async()=>buffer);await assets.ready;
      try {
        expect([...assets.failures]).toEqual([]);const model=assets.get(name);expect(model).toBeDefined();
        expect(model!.parts).toHaveLength(1);expect(model!.triangles).toBeLessThanOrEqual(600);
        const bounds=new THREE.Box3();let radius=0,minAO=1,glowingVertices=0;
        for(const part of model!.parts) {
          part.computeBoundingBox();bounds.union(part.boundingBox!);
          const p=part.getAttribute('position'),ao=part.getAttribute('_AO'),emit=part.getAttribute('_EMIT');
          expect(part.getAttribute('uv')).toBeUndefined();expect(part.getAttribute('color').itemSize).toBe(3);
          for(let i=0;i<p.count;i++){radius=Math.max(radius,Math.hypot(p.getX(i),p.getZ(i)));minAO=Math.min(minAO,ao.getX(i));expect([0,1]).toContain(emit.getX(i));glowingVertices+=emit.getX(i);}
        }
        expect(glowingVertices).toBe(name==='hillside_mine'?36:0);
        expect(radius).toBeLessThanOrEqual(.28+1e-6);expect(bounds.max.y).toBeLessThanOrEqual(.5+1e-6);expect(bounds.min.y).toBeCloseTo(0);expect(minAO).toBeLessThan(1);
        writeFileSync(`tools/models/out/${name}.validation.json`,JSON.stringify({accepted:true,fallbackReasons:[...assets.failures],triangles:model!.triangles,
          parts:model!.parts.length,normalizedBounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},normalizedRadius:radius,minAO,...(name==='hillside_mine'?{glowingVertices}:{})},null,2)+'\n');
      } finally {assets.dispose();}
    });
  }
});
